# Generated by Django 3.1.1 on 2022-04-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220423_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_secret',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
